### ISSUE TITLE
No image

### ISSUE THREAD

**Issue by DJBenson** [werthdavid/homebridge-website-to-camera#10]
This seems to have been resolved previously but I’ve just installed 1.4.1 on an RPi 3 running Raspbian 8.

`May 27 15:57:14 homekithub homebridge[24714]: [5/27/2019, 3:57:14 PM] [website-camera] Error: Failed to launch chrome!
May 27 15:57:14 homekithub homebridge[24714]: bootstrap_helper: /usr/lib/chromium-browser/nacl_helper: Cannot open ELF file!  errno=2
May 27 15:57:14 homekithub homebridge[24714]: [25220:25220:0527/155714.045740:ERROR:nacl_fork_delegate_linux.cc(315)] Bad NaCl helper startup ack (0 bytes)
May 27 15:57:14 homekithub homebridge[24714]: [25208:25208:0527/155714.049006:ERROR:browser_main_loop.cc(495)] Failed to put Xlib into threaded mode.
May 27 15:57:14 homekithub homebridge[24714]: [25208:25208:0527/155714.060614:ERROR:browser_main_loop.cc(272)] Gtk: cannot open display:
May 27 15:57:14 homekithub homebridge[24714]: TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
May 27 15:57:14 homekithub homebridge[24714]: at onClose (/usr/lib/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/lib/Launcher.js:342:14)
May 27 15:57:14 homekithub homebridge[24714]: at ChildProcess.helper.addEventListener (/usr/lib/node_modules/homebridge-website-to-camera/node_modules/puppeteer-core/lib/Launcher.js:332:60)`

**Comment by werthdavid** [comment]
So there's a problem with Chromium not starting..  Do you have the latest chromium-browser installed? If it is a desktop environment, try starting it on desktop.

**Comment by werthdavid** [comment]
Ill close this due to inactivity. If there is more information, feel free to open it again but please make sure the problem is related to the plugin and not the OS or chromium
