### ISSUE TITLE
Another "no image" issue...

### ISSUE THREAD

**Issue by ad-mq** [werthdavid/homebridge-website-to-camera#11]
I'm running homebridge on an asus tinkerboard. Debian 9.9 (stretch).

I can't find "chromium-browser" in apt, but "chromium" is installed.
I can run chromium from cli and it returns no error. Tried to change chromiumPath to "/usr/bin/chromium" but its not working.

Is "chromium" even the right package or does it need to be "chromium-browser"?

**Comment by werthdavid** [comment]
I guess "chromium" should work as well. It just needs an Chrome or Chromium Browser installed that it can run.
Is there any output provided? Does Chromium work normally when you run it on your desktop?

**Comment by werthdavid** [comment]
Ill close this due to inactivity. If there is more information, feel free to open it again but please make sure the problem is related to the plugin and not the OS or chromium
