### ISSUE TITLE
IOS 13 require a code for the camera

### ISSUE THREAD

**Issue by Stillaround** [werthdavid/homebridge-website-to-camera#12]

**Comment by werthdavid** [comment]
Ah I see what you mean... you have to provide the PIN from the config.js for the global homebridge  ("bridge.pin").

**Comment by Stillaround** [comment]
oh

**Comment by werthdavid** [comment]
Did it work for you?

**Comment by rcheramy** [comment]
I had the same issue on ios 12. I tried putting in the bridge pin and it said that pin is already added (aka the bridge).

**Comment by rcheramy** [comment]
I had the issue on iOS 12 and using the homebridge pin worked.
