### ISSUE TITLE
"Camera is not responding" between snapshots

### ISSUE THREAD

**Issue by adriancable** [werthdavid/homebridge-website-to-camera#13]
Great plugin. One issue - when touching the camera in the Home app to get the full screen view, after 20 seconds or so, the screenshot disappears and is replaced with "No Response - This camera is not responding". I suspect this is because HomeKit is expecting a live view stream connection but none is forthcoming.

Any way to tell HomeKit that the accessory doesn't support streams, only snapshots, to prevent this?

**Comment by werthdavid** [comment]
Unfortunately not.. as far as I understood HomeKit/Homebridge it expects an URL where it can connect when you tap the camera. And I haven't found any possibility to stream the browser as RTP stream..

**Comment by jb-home** [comment]
Hi,
would it be possible to create an RTSP stream using GStreamer with just a very low frame per second rate?
