### ISSUE TITLE
Increase resolution of screenshot?

### ISSUE THREAD

**Issue by schteeben95** [werthdavid/homebridge-website-to-camera#2]
Is there a way to increase the resolution of the screenshot?

**Comment by werthdavid** [comment]
Yes, there are two options.

1.:
Use a specific width and height:
```json
   {
          "name": "Google Maps Traffic",
          "url": "http://google.com",
          "height": 1334,
          "width": 750
        }
```

2.:
Use a Scale-factor.
```json
   {
          "name": "Google Maps Traffic",
          "url": "http://google.com",
          "scale": 2
        }
```


I would go for a scale factor for the following reason:
HomeApp requests a desired resolution to the plugin. This desired resolution usually differs on different devices (e.g. iPad requests an higher resolution than an iPhone). With scale=2 you just double the resolution of the screenshot. With a fixed width/height you would force a fixed resolution that could lead to black border or something..
