### ISSUE TITLE
Since Update HB rebooting every time

### ISSUE THREAD

**Issue by philmue1988** [werthdavid/homebridge-website-to-camera#20]
Hi,

first of all thank you for that nice plugin! since the update, i got the callback function error and the HB reboots new every time.

[website-camera] Loading finished, waiting 2000ms before taking screenshot
Apr 29 14:08:32 raspberrypi homebridge[28173]: [4/29/2020, 14:08:32] [website-camera] Created screenshot
Apr 29 14:08:32 raspberrypi homebridge[28173]: [4/29/2020, 14:08:32] [website-camera] Got screenshot
Apr 29 14:08:32 raspberrypi homebridge[28173]: [4/29/2020, 14:08:32] [website-camera] identify
Apr 29 14:08:32 raspberrypi homebridge[28173]: [4/29/2020, 14:08:32] TypeError: callback is not a function
Apr 29 14:08:32 raspberrypi homebridge[28173]:     at CameraAccessory.<anonymous> (/usr/local/lib/node_modules/homebridge-website-to-camera/CameraAccessory.js:28:13)
Apr 29 14:08:32 raspberrypi homebridge[28173]:     at CameraAccessory.emit (events.js:223:5)
Apr 29 14:08:32 raspberrypi homebridge[28173]:     at Accessory.<anonymous> (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:85:12)
Apr 29 14:08:32 raspberrypi homebridge[28173]:     at Accessory.emit (events.js:223:5)
Apr 29 14:08:32 raspberrypi homebridge[28173]:     at Accessory.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
Apr 29 14:08:32 raspberrypi homebridge[28173]:     at Accessory._this._identificationRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:259:12)
Apr 29 14:08:32 raspberrypi homebridge[28173]:     at Identify.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:248:16)
Apr 29 14:08:32 raspberrypi homebridge[28173]:     at Identify.emit (events.js:223:5)
Apr 29 14:08:32 raspberrypi homebridge[28173]:     at Identify.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
Apr 29 14:08:32 raspberrypi homebridge[28173]:     at Identify.Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:614:12)

Could you help out?

Phil

**Comment by werthdavid** [comment]
please try homebridge-website-to-camera@1.5.2
