### ISSUE TITLE
The camera is not responding

### ISSUE THREAD

**Issue by inquisition** [werthdavid/homebridge-website-to-camera#21]
Hello and thank you for your great plugin that used to work very good.
Since a few days I get this error in the logs and I am unable to connect to the camera from the Home app. 
Here is the error on the Homebridge logs: "One of your plugins incorrectly registered an external accessory using the platform name (website-camera) and not the plugin identifier. Please report this to the developer!"

Thanks!

**Comment by werthdavid** [comment]
Hey, can you provide your config please? Do you use more than one camera?

**Comment by werthdavid** [comment]
Never mind, I found the issue!

**Comment by werthdavid** [comment]
Please try homebridge-website-to-camera@1.5.3 (maybe the cameras have to be added again to Home)

**Comment by inquisition** [comment]
1.5.3 fixes the issue ! And yes I had to add the camera again. Thank you !
Now I can check how the beach looks before going for a swim :-)

**Comment by werthdavid** [comment]
Nice :D I use it to check the traffic before leaving for or from work.
