### ISSUE TITLE
Confirmation of cookies on the website

### ISSUE THREAD

**Issue by bananajoe86** [werthdavid/homebridge-website-to-camera#30]
I wanted to get a route on Google maps. Now Google will inform you that cookies are being used and I will ask you to confirm. Does anyone have any idea how I can get this confirmation away so that I can display my picture?

**Comment by werthdavid** [comment]
Oops... Do you have a graphical desktop available? If so, I can add an option that starts Chrome with GUI so you can click that away. Afterwards it should be stored and not come up again.

**Comment by bananajoe86** [comment]
No, only the Raspbian Light without desktop

**Comment by werthdavid** [comment]
now you can inject custom JS to remove banners
