### ISSUE TITLE
Plugin for Docker Version - oznu/homebridge

### ISSUE THREAD

**Issue by DonMaverick** [werthdavid/homebridge-website-to-camera#31]
Hi,
great Plugin. But i am unable to use it on my Docker Container. (Respberry)
- oznu/homebridge
- Alpine Linux (3.12.4) 

I am unable to install chromium.
Can you please support me?

Thanks a lot
DON

**Comment by werthdavid** [comment]
What have you tried so far? Can you show me your Dockerfile?

**Comment by DonMaverick** [comment]
What i did....

apk update 
apk upgrade

I tried:
/homebridge # apk add --no-cache  chromium --repository=http://dl-cdn.alpinelinux.org/alpine/v3.10/main
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/armhf/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/armhf/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/armhf/APKINDEX.tar.gz
ERROR: unable to select packages:
  chromium (no such package):
    required by: world[chromium]

I am unable to install Cromium :-(

**Comment by werthdavid** [comment]
Have you seen this?
https://stackoverflow.com/questions/57714810/docker-nodealpine-12-how-to-install-chromium-73-in-dockerfile

**Comment by DonMaverick** [comment]
I tried :-(

/homebridge # apk add --no-cache  chromium --repository=http://dl-cdn.alpinelinux.org/alpine/v3.10/main
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/armhf/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/armhf/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/armhf/APKINDEX.tar.gz
ERROR: unable to select packages:
  chromium (no such package):
    required by: world[chromium]
/homebridge #

**Comment by werthdavid** [comment]
Did you manage to install chromium?

**Comment by harryslapalot** [comment]
I have the same problem. I am using OZNU Homebridge in Docker on my Synology and I am at a loss how to install chromium. Can anybody help me out?
