### ISSUE TITLE
Cannot add camera in Homekit

### ISSUE THREAD

**Issue by Walker-SW** [werthdavid/homebridge-website-to-camera#34]
As described in the read.me the camera might not be seen by default.
So I did the following as suggested:

    Press + on top right corner in Home-App
    Press Add device
    Press Code missing
    Select Camera

Nevertheless the Homekit-App still asks me for the 8 digit code which I don't have.
If I click cancel I can close the code window but the camera was not added.

Any suggestions?
THANX

**Comment by Walker-SW** [comment]
> 
> 
> As described in the read.me the camera might not be seen by default.
> So I did the following as suggested:
> 
> ```
> Press + on top right corner in Home-App
> Press Add device
> Press Code missing
> Select Camera
> ```
> 
> Nevertheless the Homekit-App still asks me for the 8 digit code which I don't have.
> If I click cancel I can close the code window but the camera was not added.
> 
> Any suggestions?
> THANX

Issue solved. Realized that in the log file I can find the Code generated by homebridge.
The camera appears but unfortunately the camera icon shows "no answer" :(

**Comment by Jackstone188** [comment]
Hey, i cant find the code. Where did you find the code?

**Comment by werthdavid** [comment]
The code that is logged when homebridge is started straight below the qr-code
