### ISSUE TITLE
Doesn't trigger on Apple TV

### ISSUE THREAD

**Issue by FirePanther** [werthdavid/homebridge-website-to-camera#36]
I've created two dummy cameras, one with this plugin and one with the ffmpeg homebridge plugin.
In the logs I can see, that the ffmpeg plugin responds immediately when I swipe to the Camera on the Apple TV, doesn't matter on which interface.
The website to camera plugin shows me the logs only when I open it on my iPhone (but also shows me a "No Response" watermark).
![iphone](https://user-images.githubusercontent.com/1711106/141851571-b394499a-b1af-49ae-9b5d-41d4d3795a65.png)
![tv](https://user-images.githubusercontent.com/1711106/141851699-2eb8a507-0944-43b7-91d6-98aaa4863194.jpg)

**Comment by werthdavid** [comment]
Thanks, now that I got an Apple TV as well I'll look into it!

**Comment by werthdavid** [comment]
Working on it... The thing is, that tvOS doesn't trigger "handleSnapshotRequest" but instead immediately tries to start the stream (which is currently not supported by this plugin...).

**Comment by werthdavid** [comment]
Please try the new version 2.0.0
