### ISSUE TITLE
Motion Functionality

### ISSUE THREAD

**Issue by FirePanther** [werthdavid/homebridge-website-to-camera#37]
The motion functionality would be awesome. This is also integrated in some other homebridge camera plugins and this way someone could open the camera on the apple tv automatically.
A way to do this would be to http request a "start" and a "stop" url/rest api, depending on the topic which is shown on that website you could show the camera if someone rang the bell, weather warnings, on specific times, on alarms/timers…

**Comment by werthdavid** [comment]
Not sure how that works exactly.. Can you provide more information? (auch auf deutsch, wenn es dadurch einfacher wird)

**Comment by FirePanther** [comment]
Hi :) sorry für die stark verspätete Antwort, hatte ewig nichts mehr mit Homebridge gearbeitet.
Die Motion Funktion siehst du z.B. auch im [ffmpeg camera Homebridge Plugin](https://www.npmjs.com/package/homebridge-camera-ffmpeg#optional-parameters).
Man kann dadurch z.B. mit einem Dummy Switch auf Homebridge eine "Motion" triggern (bei einer realen Kamera heißt es, es wurde eine Bewegung erkannt, dadurch springt z.B. auf Apple TV die Kamera auf als Picture in Picture, klein, während man z.B. einen Film schaut).
Diese Funktion würde ermöglichen, dass man z.B. eine bestimmte Website anzeigen könnte (beispielsweise eine Maps Seite), wenn z.B. ein Freund oder Partner in der Nähe geortet wurde, man könnte z.B. den Lieferando Lieferantenstandort anzeigen, wenn eine E-Mail von Lieferando empfangen wurde (oder auch andere E-Mail triggers, wie z.B. "Amazon ist noch 8 Stopps entfernt von dir), man könnte sonstige Notification-ähnlichen Anzeigen aufploppen lassen ("Es klingelte an der Tür", "neue E-Mail von Arbeitgeber", "Meeting: Pairing mit Arbeitskollege", "Der Download ist fertig", …).

**Comment by werthdavid** [comment]
Ah interessant.. Zwischenzeitlich habe ich auch einen AppleTV mit dem ich testen kann 😛  Allerdings mache ich auch nicht mehr viel mit der Homebridge sondern alles mit Home Assistant.. Ist halt die Frage wie die Motion getriggert werden soll. Per virtuellem Switch ist wohl eher kein Problem aber eben auch etwas witzlos. Hmmm man könnte z.B. das letzte Bild mit dem neuen Bild vergleichen und wenn eine Veränderung von 5% stattgefunden hat den Alarm triggern... Ich denke nochmal darüber nach ;-)

**Comment by FirePanther** [comment]
Ich habe mir nicht genau angeschaut wie website-to-camera funktioniert, aber ich denke es schießt keine Screenshots, wenn du dir die Kamera nicht anschaust (?)
Das Interessante an Motion Trigger ist, dass es halt von überall aus getriggert werden könnte und zwar live.
Ich denke wenn du z.B. den HTML Source Code vergleichen müsstest, dann wäre es eher polling mit einem Intervall, d.h. wenn jemand die Tür klingelt würde womöglich das Icon erst nach 5-10 Sekunden erscheinen :D ich denke deshalb haben andere Anbieter Dummy Switches. Ich denke jedoch dass Du beispielsweise einen Webserver hast, d.h. man könnte sogar via HTTP Request eine Motion triggern. (Dann bräuchte man noch einen WebRequest um die Motion zu stoppen, also sowas wie den Dummy Switch auszuschalten.)
Falls du noch Fragen haben solltest, falls ich es hinbekomme, könnte ich versuchen ein Video aufzunehmen zu dem Thema und herauszufinden, was sonstige Vorteile von Motion sind, neben der Apple TV integration (wahrscheinlich iPhone Notifications und vielleicht sogar mehr).

**Comment by werthdavid** [comment]
Habe eben mal bei ffmpeg rein gespickelt, wäre wohl nicht übermäßig kompliziert so eine Motion zu triggern. 
Einen Web-Server nutzt dieses Plugin hier nicht direkt, da es ja Chrome startet und steuert. Allerdings läuft das ja alles unter node, da kann man natürlich relativ einfach auf requests horchen. 
Was ich nicht ganz verstehe ist was ein Dummy Switch bringt. Wie wird der dann getriggert? Über eine HomeKit Automatisierung?
