### ISSUE TITLE
chromium not working

### ISSUE THREAD

**Issue by henryhuisman** [werthdavid/homebridge-website-to-camera#42]
newbie over here, so I hope you can help me. 
Installing chromium seems to work fine, but when testing it like you discribed, it gives this in return:
[1229/181723.401153:ERROR:elf_dynamic_array_reader.h(61)] tag not found
Trace/breakpoint trap

How can I solve this?
Thank you in advance

**Comment by werthdavid** [comment]
Please try again with latest 2.0.4
