### ISSUE TITLE
Display images as camera

### ISSUE THREAD

**Issue by holocronology** [werthdavid/homebridge-website-to-camera#43]
There are two branches that have forked off this. Both are geared towards displaying an image as a camera, rather than a website. This leads to a few questions:

1. Do these branches still require the chromium install for homebridge?
2. Can the features be rolled into this one plug-in?
3. If yes to the above, can it be done with an option to NOT install chromium?

Thanks.

**Comment by werthdavid** [comment]
1. Nope, chromium is required to get a screenshot of a website.
2. Yes, I like the idea of displaying an image!
3. chromium has to be installed independent of that plugin anyway so yes, that can be possible

**Comment by werthdavid** [comment]
Actually this should work out of the box... instead of the URL you just have to provide the full path to the image!
