### ISSUE TITLE
Version for Debian Bullseye lite

### ISSUE THREAD

**Issue by guitardoc** [werthdavid/homebridge-website-to-camera#44]
Hello,

The Chromium-Browser does not work anymore on Debian Bullseye (probably due to BlueAlsa no longer being part of the Bullseye installation - BlueAlsa cannot be installed separately either).

The only way on Bullseye is to use Chromium instead of Chromium-Browser. Is it possible to have an update using Chromium instead of Chromium-Browser?

Thank you.

**Comment by werthdavid** [comment]
Hey, are you talking about (google) chrome? Did you try if it works? As Chrome and Chromium are basically the same, I guess it should work right away

**Comment by guitardoc** [comment]
Hello,
Yes, I tried it. I installed chromium instead of chromium-browser and then installed the homebridge-website-to-camera plugin. It did not work. However, I am not sure if I entered the correct path to chromium as it might get installed differently to chromium-browser.
Thank you for looking into this.

PS. I am not sure if chromium installs correctly either. When entering 
$ chromium
it aborts with error: „Missing X server or $DISPLAY“

**Comment by werthdavid** [comment]
The error is fine, it states that you don't have a graphical environment (Desktop) available, which is expected as you're running the command from a (remote-)shell.

What error do you get from the plugin?
You should locate the "chromium"-executable on your system and provide the path in the config e.g.
"chromiumPath": "/usr/bin/chromium"

**Comment by guitardoc** [comment]
Dear David,
I just tried it and got it to work. It seems I had the path to the chromium executable wrong.
Thank you very much for looking into this!

**Comment by werthdavid** [comment]
That's great, you're welcome!
