### ISSUE TITLE
TimeoutError

### ISSUE THREAD

**Issue by borisdebusscher** [werthdavid/homebridge-website-to-camera#5]
Hey! After logging "Going to page:..." in my terminal, I constantly have the following error: TimeoutError: Navigation Timeout Exceeded: 10000ms exceeded

**Comment by MrDrache333** [comment]
Same here...:/

**Comment by borisdebusscher** [comment]
😪

**Comment by MrDrache333** [comment]
I tryed something...if you only use http instead of https it works...But if you want to open any Website with https it fails :/

**Comment by borisdebusscher** [comment]
Mmmm good to know, I'll look into it thanks!

**Comment by borisdebusscher** [comment]
it's maybe just a timeout issue, if I disable timeout it could work

**Comment by werthdavid** [comment]
Can you provide the website you're using?

**Comment by kaosmagix** [comment]
I have the same issue with a regular (local) http site. It would work for me if the time-out could be disabled or set in a parameter

**Comment by werthdavid** [comment]
Ok guys I made version 1.3.0 where you can configure your timeout for the page to wait. Also it is considered ok if there is up to 2 network requests still pending. Let me know if it helped
