### ISSUE TITLE
Starting the plugin leads to 100% CPU

### ISSUE THREAD

**Issue by guitardoc** [werthdavid/homebridge-website-to-camera#52]
The plugin used to work flawlessly for years.
However, for about two weeks now, the plugin leads to 100% CPU. When I stop the plugin, the CPU is back to normal (about 10% on a Proxmox). I think there have been some changes to the Homebridge System, maybe this triggered it?

**Comment by werthdavid** [comment]
I will take a look. Could it be that maybe the Chrome was updated and not Homebridge?

**Comment by guitardoc** [comment]
Yes, that could be possible.

**Comment by werthdavid** [comment]
Can u provide some more information about config and versions used?
What version of Hombridge, did u update recently, OS and Chromium version, also Hardware (raspberry?).
I just did a fresh install on my Intel N100 based mini-pc (x64) with Ubuntu 24 and Google Chrome (not Chromium) and it works fine for me at least..

**Comment by guitardoc** [comment]
Yes, of course.

I am on 
- Debian GNU/Linux Bookworm (12) on a Proxmox (2 allocated kernels, 4GB allocated RAM).
- Homebridge: v1.8.4 · UI v4.57.1
- Plugin v2.0.4
- Chromium 128.0.6613.113 built on Debian GNU/Linux 12 (bookworm)

I updated the whole system about a week ago and that was when the problem occurred first.

Edit: I am still on node v20.11.0 due to another plugin (Homebridge Eufy Security) not providing some features I need with higher version of node.

**Comment by werthdavid** [comment]
One more question: when you run `htop` for example, which process has the high CPU usage? Homebridge (node) or Chromium?
Anyway, I created a new version 2.0.5 can you try that out?

**Comment by guitardoc** [comment]
I think Chromium is the culprit:
<img width="1428" alt="image" src="https://github.com/user-attachments/assets/b76af1b6-418c-4c71-b916-f414048df5a6">


I don't know how to install the new version?

**Comment by werthdavid** [comment]
Are you using HomeBridge UI?

**Comment by guitardoc** [comment]
Yes

**Comment by werthdavid** [comment]
Now there should be an update visible when you browse to the plugins page?

**Comment by guitardoc** [comment]
Yes, I could update the plugin now.
No, it did not help the cpu load going up to 100% unfortunately... :-(

**Comment by guitardoc** [comment]
Ich sehe gerade, dass du auch wie ich der deutschen Sprache mächtig bist, da greife ich mal darauf zurück, geht schneller... :-)
Es gab gerade ein Update des Homebridge UI. Ich will mich mal nicht zu früh freuen, aber seitdem funktioniert das Plugin wieder. Warum das so ist kann ich nur raten... Jetzt liegen die CPU-Auslastungen zwischen 4 und 40%, je nachdem ob das Plugin gerade Daten holt oder nicht. Also war möglicherweise ein Fehler auf Seiten der Homebridge das Problem.

**Comment by werthdavid** [comment]
Okay, ich verstehe leider überhaupt nicht wo das herkommt, aber dann hoffen wir mal, dass es jetzt wieder klappt und auch so bleibt 🙈

**Comment by guitardoc** [comment]
Also bisher funktioniert es wieder so wie es jahrelang vorher auch funktioniert hat. Ich kann es auch nicht nachvollziehen, wie das entstanden ist, vor allem scheint es ja nicht viele Anwender betroffen zu haben... Ich würde den Punkt jetzt schließen, offensichtlich hatte es ja gar nichts mit dem Plugin zu tun. Danke dafür, dass du es dir angesehen hast!
