### ISSUE TITLE
No picture in camera

### ISSUE THREAD

**Issue by RienduPre** [werthdavid/homebridge-website-to-camera#6]
Hi,

I use a homebridge on a RPi. Chromium is running fine and I can open url's on the desktop of the RPi.
I see no related errors in the log, just some initialization messages, which seems to be normal

When I add a camera I see
[website-camera] Starting new instance of Chromium: /usr/bin/chromium-browser
[website-camera] Chromium started
[website-camera] Opening new page

For both of the camera's

The problem is that there is no web page shown in the homekit app.

![image](https://user-images.githubusercontent.com/9009949/52371606-50a42700-2a56-11e9-90da-6ce839a48098.png)

Thank you for any help you can give me
Rien

**Comment by werthdavid** [comment]
I'll have a look

**Comment by RienduPre** [comment]
Any clues yet?

**Comment by werthdavid** [comment]
Sorry for the delay... My homebridge on RPi3 crashed and the one running on RPi Zero is to weak for chromium.. Currently struggeling setting up a new Homebridge on the Pi 3, my iPhone won't find it.. But I'm on it!

**Comment by werthdavid** [comment]
For me everything works fine with a fresh installation...
Log Output looks like this:
[2/18/2019, 12:41:13 PM] [website-camera] identify
[2/18/2019, 12:41:19 PM] [website-camera] Starting new instance of Chromium: /usr/bin/chromium-browser
[2/18/2019, 12:41:28 PM] [website-camera] Chromium started
[2/18/2019, 12:41:28 PM] [website-camera] Opening new page
[2/18/2019, 12:41:29 PM] [website-camera] Setting Viewport to 960x540
[2/18/2019, 12:41:29 PM] [website-camera] Going to page: http://github.com
[2/18/2019, 12:41:32 PM] [website-camera] Created screenshot
[2/18/2019, 12:41:32 PM] [website-camera] Got screenshot


What website are you calling? Is it a RPi 3?

**Comment by RienduPre** [comment]
Hi,

I use an RPi 3 

See below my config.json part of the plugin

 {
            "platform": "website-camera",
            "cameras": [
                {
                    "name": "Google Maps Traffic",
                    "url": "http://google.com",
                    "height": 1334,
                    "width": 750
                },
                {
                    "name": "Google Maps Traffic #2",
                    "url": "http://google.com",
                    "scale": 1
                }
            ]
        }

**Comment by werthdavid** [comment]
Can you (first stop and then) start homebridge manually with "homebridge -D" and the open the Home App (so a refresh is triggered) and the provide the log output?

**Comment by werthdavid** [comment]
Another idea would be to add the path of the Chromium-executable:

config.json
```json
"platforms": [
         {
         "platform": "website-camera",
         "cameras": [
            {
               "name": "Website 1",
               "url": "http://maps.google.com",
               "chromiumPath": "/usr/bin/chromium-browser"
            }
         ]
      }
  ]
```

**Comment by RienduPre** [comment]
Hi,
Sorry for the late response.
With debug on, there is no more logging than the ones I see in normal mode.
Specifying the chromium path does not have any effect either.

**Comment by werthdavid** [comment]
Hey, 
so I found a Bug with puppeteer
https://github.com/GoogleChrome/puppeteer/issues/1409

I'll release a new version for you

**Comment by werthdavid** [comment]
Please install 1.2.2 and try again!

**Comment by RienduPre** [comment]
Sorry for the late response (was on vacation)
Issue is solved !!
Thank you very much.
