### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by BOMAMI** [werthdavid/homebridge-website-to-camera#7]
![graph](https://user-images.githubusercontent.com/46925730/54426720-d5025d80-4718-11e9-9f34-1706b09c328e.jpg)
Hi,
thanks for this plugin.
I'm trying to use the plugin to display a website that runs locally on an arduino mega.
This website shows the temperature history of my heating system.
So far, this has worked only once. I think it's because the screenshot is done too fast. On a normal browser, it takes about 10 seconds for the counts to be displayed.  Setting Timeout to 10 seconds did not work. According to the log, the snapshot is already generated one second after the call.
Could a proper waiting time help here?

**Comment by werthdavid** [comment]
Ok I guess after loading all network resources the page does some rendering (PWA). The timeout only affects the time until all resources are loaded. I'll have to add another flag for a render-timeout

**Comment by werthdavid** [comment]
Please try the new option: renderTimeout

**Comment by werthdavid** [comment]
published in 1.4.0

**Comment by BOMAMI** [comment]
Hi werthdavid,
thanks for your support
I tryed the new renderTimout and so far it works!
![Image-1](https://user-images.githubusercontent.com/46925730/54560830-80363f80-49c3-11e9-8448-06ad1989f9f3.jpg)

Thank you very much!
regards

**Comment by werthdavid** [comment]
Cool, glad I could help!
