### ISSUE TITLE
Parse Login / API?

### ISSUE THREAD

**Issue by Glynnryan** [werthdavid/homebridge-website-to-camera#8]
Although more of a help request than an issue, I am pointing the plugin to an site on my local network, which requires login details to be entered on first login. I've tried login in from Chromium browser first, but when viewing the feed through the plugin, it displays the login screen for my locally hosted site.

Any idea how to bypass this or somehow send username and password detail through? The application I am trying to view does have API functionality, if that might help?

Thanks in advance!

**Comment by Glynnryan** [comment]
Edit - Tried to set the best title. ¯\_(ツ)_/¯

**Comment by martijnmnnk** [comment]
Is the site asking for your credentials through http authorisation? If yes, then you can login like this:
http://username:password@www.domain.com

**Comment by Glynnryan** [comment]
@Brklnbnc Thanks for that! I got it working thanks to your suggestion!
